# docker file for running postgresql in a container
version: '3.1'
services:
  postgres:
    image: postgres:9.6
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - /tmp/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

